In [3]:
def my_div(a,b):
    try:
        x = a/b
    except ZeroDivisionError:
        print('Error: ZeroDivisionError')
    else:
        print(x)
    
my_div(5,0)

Error: ZeroDivisionError


In [8]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

'''for s in subjects:
    for v in verbs:
        for o in objects:
            print(s,v,o)'''
            
sen_list = [(s+' '+v+' '+o) for s in subjects for v in verbs for o in objects]
for sen in sen_list:
    print(sen)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [64]:
import numpy as np
lst=[1,2,3,4,5]

def vandermonde(inp_lst,order):
    nlst=[]
    ln=len(inp_lst)
    
    if order == True:
        print('Vandermonde Matrix in Increasing Order')
        for i in inp_lst:
            temp=[]
            for j in range(ln):
                temp.append(pow(i,j))
            nlst.append(temp)
        narr=np.array(nlst)
        print(narr)
    else:
        print('Vandermonde Matrix in Decreasing Order')
        for i in inp_lst:
            temp=[]
            for j in range(ln):
                temp.append(pow(i,ln-j-1))
            nlst.append(temp)
        narr=np.array(nlst)
        print(narr)
        

vandermonde(lst,True)

Vandermonde Matrix in Increasing Order
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
